# Generated by Django 2.2.6 on 2019-10-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='current_plan',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
